### PR TITLE
Fix errors

### PR DESCRIPTION
**Pull request by lilkidsuave**
Screenshot_20240618_044229_Brave

### CODE REVIEW

**Comment by waschinski** [comment]
Your PR looks promising, why did you end up closing it? :)

**Comment by lilkidsuave** [comment]
The original was just meant to fix the output path

**Comment by lilkidsuave** [comment]
Its open again if you want
Warning: This now has github actions

**Comment by waschinski** [comment]
Thanks a lot for contributing, I will have a closer look later and will then merge your PR.

**Pull request merged**
