### PR TITLE
Add Timezones

### PR DESCRIPTION
**Pull request by lilkidsuave**

### CODE REVIEW

**Comment by waschinski** [comment]
All this code is only so the log will display valid_until in the proper time zone, isn't it?

Also, some general advice: I'd recommend adding a proper description to out of the blue PRs. There's also too many changes in the docker compose file as well as the Dockerfile when you are basically just adding env variables.

**Comment by lilkidsuave** [comment]
Mostly. It also shows the certificate expire date to the user.
Too many changes to the dockerfile is reasonable, but the docker compose is a required fix.
`docker run -d --network host  --privileged --name cosmos-server -h cosmos-server --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /:/mnt/host -v /var/lib/cosmos:/config azukaar/cosmos-server:latest`
The external bits aren't needed as the cosmos default install uses binds.

**Comment by lilkidsuave** [comment]
https://github.com/waschinski/cosmos-cert-extractor/pull/3/commits/fa1ace5661b68e2c1000951ce2706f605ee0d407

**Comment by lilkidsuave** [comment]
man why do i bother

**Comment by waschinski** [comment]
You are absolutely right about cosmos using a bind mount per default. Thanks for pointing that out. I personally had it set up using a volume so I probably should adjust that part accordingly.

AdGuard is using a volume though and at least for that `external:true` should make sense.

Btw sharing this kind of information about your changes upfront is what I was talking about before.

If you are not open to discussions and can't accept that others might disagree with your changes I don't know man. I am pretty sure on other, larger projects a PR like this would simply get closed and some might not even respond.

**Comment by lilkidsuave** [comment]
> You are absolutely right about cosmos using a bind mount per default. Thanks for pointing that out. I personally had it set up using a volume so I probably should adjust that part accordingly.
> 
> AdGuard is using a volume though and at least for that `external:true` should make sense.
> 
Adguard doesn't even use volumes by default 
https://hub.docker.com/r/adguard/adguardhome

**Comment by waschinski** [comment]
My bad, you are right. I was assuming it does obviously due to my habit of using volumes over directories.

**Pull request closed without merging**
